# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Setup tmate session

      uses: mxschmitt/action-tmate@v3 



# Controls when the workflow will run

  # Triggers the workflow on push or pull request events but only for the "main" branch


  
    

  # Allows you to run this workflow manually from the Actions tab


# A workflow run is made up of one or more jobs that can run sequentially or in parallel

  # This workflow contains a single job called "build"
  
    # The type of runner that the job will run on
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      

      



      #
      



